[project]
name = "python-mastery-problems"
version = "0.1.0"
description = "20 progressive Python exercises for fluency"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "pytest>=8.0.0",
    "pandas>=2.2.0",
]
